version: '3.2'
services:
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./prometheus:/etc/prometheus/
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
            - 192.168.137.150:9090:9090
        restart: always
        depends_on:
            - alertmanager

    node-exporter:
        image: prom/node-exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
        ports:
            - 192.168.137.150:9100:9100
        restart: always

    grafana:
        image: grafana/grafana
        depends_on:
            - prometheus
        ports:
            - 192.168.137.150:3000:3000
        volumes:
            - ./grafana:/var/lib/grafana
            - ./grafana/provisioning/:/etc/grafana/provisioning/
        user: root
        restart: always

    blackbox:
        image: prom/blackbox-exporter
        command:
            - --config.file=/etc/blackbox/blackbox.yml
        ports:
            - 9115:9115
        volumes:
            - ./blackbox:/etc/blackbox
        restart: always

    alertmanager:
        image: prom/alertmanager:v0.21.0
        ports:
          - 192.168.137.150:9093:9093
        volumes:
          - ./alertmanager/:/etc/alertmanager/
        restart: always
        command:
          - --config.file=/etc/alertmanager/config.yml
          - --storage.path=/etc/alertmanager/data
        user: root